sudo: required
dist: trusty
language: node_js
node_js:
  - 6
  - 5
  - 4
  - 3
  - 2
  - 1

script: npm test

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start